name: Rails Tests

env:
  HOST: localhost

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install Yarn
      run: yarn install

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.6
        bundler-cache: true

    # - name: Bundle Install
    #   run: |
    #     gem install bundler
    #     bundle config path vendor/bundle
    #     bundle check || bundle install --jobs 4 --retry 3

    - name: Prepare Database
      env:
        RAILS_ENV: test
      run: bundle exec rails parallel:setup

    - name: Build and test with Rake
      env:
        RAILS_ENV: test
      continue-on-error: false
      run: bundle exec rails parallel:spec
